#!/usr/bin/env python3
"""Extract the COMPLETE 6-lane Excitebike track layout from ground-truth RAM dumps.

The game streams the track into a 6-lane x 64-column circular buffer at ram_0400 (lane page base
= 0x400 + lane*0x40, indexed by the column counter 0xE0). At every frame, buffer index 0xE0 holds
the terrain tile for the bike's CURRENT absolute column (= cumulative unwrapped 0xE0) for ALL six
lanes simultaneously (the lanes scroll together). Walking a full race therefore reveals the entire
track: terrain[lane][column] for every lane and every column the bike passes.

This is the actual ROM level data (the buffer is filled from ROM). It is cross-validated: the TAS and
the manual dumps agree on every shared cell (0 diffs), proving the array is track-intrinsic, not
run-specific. We take the UNION of both dumps for full column coverage (the manual runs a few columns
further at the finish).

terrain tile semantics (used by the section machinery, sub_E73B @ $E73B):
  - value >= 0x40  -> a SECTION-START marker; section = ((value - 0x40) >> 2) + 1
  - value <  0x40  -> ordinary ground/height tile (e.g. 0x3B/0x3D/0x3B..0x3D flat ground)

Usage:  python3 tools/extract_track_layout.py            # writes source/track_layout.hpp
        python3 tools/extract_track_layout.py --check     # just report, don't write
"""
import os, sys
os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
F = 2048
NLANES = 6

def reconstruct(name):
    d = open(name, 'rb').read()
    fr = [d[i*F:(i+1)*F] for i in range(len(d)//F)]
    track = {}
    e0u = 0; prev = fr[0][0xE0]
    for f in fr:
        e0u += (f[0xE0] - prev) & 0x3F; prev = f[0xE0]
        c = f[0xE0]
        for lane in range(NLANES):
            track[(lane, e0u)] = f[0x400 + lane*0x40 + c]
    return track

def main():
    dumps = [n for n in ('tas.ram', 'manual.ram') if os.path.exists(n)]
    if not dumps: sys.exit("need tas.ram and/or manual.ram")
    merged = {}; conflicts = 0
    for n in dumps:
        t = reconstruct(n)
        for k, v in t.items():
            if k in merged and merged[k] != v: conflicts += 1
            merged[k] = v
    ncol = max(c for (_, c) in merged) + 1
    print(f"dumps={dumps} lanes={NLANES} columns={ncol} cells={len(merged)} cross-conflicts={conflicts}")
    if conflicts: sys.exit("CONFLICT between dumps -- track not intrinsic; investigate")
    # build dense array; columns never seen default to 0x3B (flat ground filler)
    arr = [[merged.get((lane, c), 0x3B) for c in range(ncol)] for lane in range(NLANES)]
    if '--check' in sys.argv:
        # show section markers per lane
        for lane in range(NLANES):
            marks = [(c, arr[lane][c], ((arr[lane][c]-0x40)>>2)+1) for c in range(ncol) if arr[lane][c] >= 0x40]
            print(f"lane{lane}: {len(marks)} section markers")
        return
    out = ["#pragma once",
           "// GENERATED by tools/extract_track_layout.py from tas.ram + manual.ram (cross-validated, 0 conflicts).",
           "// The complete 6-lane Excitebike race track: terrain tile per (lane, cumulative column).",
           "// tile>=0x40 => section-start marker, section=((tile-0x40)>>2)+1; tile<0x40 => ground/height.",
           "#include <cstdint>", "#include <cstddef>", "namespace excitebike {",
           f"static constexpr size_t kTrackLanes = {NLANES};",
           f"static constexpr size_t kTrackColumns = {ncol};",
           "static constexpr uint8_t kTrack[kTrackLanes][kTrackColumns] = {"]
    for lane in range(NLANES):
        body = ",".join(f"0x{v:02X}" for v in arr[lane])
        out.append(f"  {{{body}}},")
    out += ["};", "} // namespace excitebike", ""]
    with open("source/track_layout.hpp", "w") as f: f.write("\n".join(out))
    print(f"wrote source/track_layout.hpp ({NLANES}x{ncol})")

if __name__ == "__main__":
    main()
