#!/usr/bin/env python3
"""
Extract the on-path track profile of the reference race from tas.ram (handoff §8, path 2).

Because the optimal route is geometry-forced (no lane slack -- proven), the terrain along the path is a
deterministic function of the bike's absolute X. This tool walks tas.ram, reconstructs absolute posX
(blockTransitions*256 + 0x50 + 0x394/256), and segments the race into contiguous runs of
(airMode, slope) -- i.e. flat-ground / ramp / airborne / downhill stretches -- recording for each the
frame & posX span and the velX behaviour. Output is a human-readable segment map (the track skeleton
the native engine must follow) and the jump launch/land pairs.

Usage: python3 tools/extract_track.py [path/to/tas.ram]   (default: ./tas.ram)
"""
import sys
F = 2048
path = sys.argv[1] if len(sys.argv) > 1 else 'tas.ram'
T = open(path, 'rb').read()
NF = len(T) // F
def fr(f): return T[f*F:(f+1)*F]

# Reconstruct absolute posX exactly as the game's _bikePosX does (count 0x4E toggles).
blk = 0; prev4E = fr(0)[0x4E]
absx = []
for f in range(NF):
    b = fr(f)
    if b[0x4E] != prev4E: blk += 1
    prev4E = b[0x4E]
    absx.append(blk*256 + b[0x50] + b[0x394]/256.0)

# Segment by (airMode!=0, slope).
def key(b): return (1 if b[0xB0] != 0 else 0, b[0xD4])
segs = []
s = 0
for f in range(1, NF+1):
    if f == NF or key(fr(f)) != key(fr(s)):
        b0 = fr(s); b1 = fr(f-1)
        v0 = b0[0x94]*256+b0[0x90]; v1 = b1[0x94]*256+b1[0x90]
        segs.append((s, f-1, 'AIR' if b0[0xB0] else 'GND', b0[0xD4], absx[s], absx[f-1], v0, v1, b0[0xAC], b1[0xAC]))
        s = f

print(f"# Track profile of the reference race ({NF} frames, finishes at the Race Over flag)\n")
print(f"{'frames':>11}  {'kind':3} {'slope':>5}  {'posX_start':>10} {'posX_end':>10}  {'velX':>9}  {'angle':>7}")
for (s,e,k,sl,x0,x1,v0,v1,a0,a1) in segs:
    print(f"{s:5d}-{e:5d}  {k:3} {sl:5d}  {x0:10.2f} {x1:10.2f}  {v0:4d}->{v1:4d}  {a0:3d}->{a1:3d}")

# Jump launch/land pairs (ground->air->ground)
print(f"\n# Jumps (airborne stretches): {sum(1 for x in segs if x[2]=='AIR')}")
for (s,e,k,sl,x0,x1,v0,v1,a0,a1) in segs:
    if k == 'AIR':
        print(f"  launch frame {s:5d} @posX {x0:8.2f}  -> land frame {e+1:5d} @posX {x1:8.2f}  ({e-s+1} frames aloft, velX {v0})")

# Downhill (coast) over-cap segments: ground stretches where velX exceeds the 832 flat cap.
print("\n# Over-cap (downhill) ground stretches (velX > 832):")
for (s,e,k,sl,x0,x1,v0,v1,a0,a1) in segs:
    if k == 'GND' and max(v0,v1) > 832:
        print(f"  frames {s:5d}-{e:5d} @posX {x0:8.2f}-{x1:8.2f}  slope {sl}  velX {v0}->{v1}")

# ---- Emit a C++ track-data header for the engine (reward-fidelity-first) -------------------------
# Airborne intervals keyed on absolute posX (valid: velX is pinned at 832 through the jump phase, so the
# bike's posX trajectory is deterministic) and the §4g over-cap +256 boost positions (terrain type 0x13).
if __name__ == '__main__' and '--emit-header' in sys.argv:
    # airborne runs -> (launch_absX, land_absX]
    # Keyed on START-OF-FRAME posX (= previous frame's posX), so the engine can decide airMode/boost
    # BEFORE the speed+position update of the launch frame (the boost must affect that frame's posX).
    # For an airborne run of frames [s, e]: launchX = posX entering frame s (absx[s-1]); landX = posX
    # entering the first ground frame after (absx[e]).
    intervals = []
    f = 0
    while f < NF:
        if fr(f)[0xB0] != 0:
            s = f
            while f < NF and fr(f)[0xB0] != 0: f += 1
            e = f - 1
            intervals.append((absx[s-1] if s > 0 else absx[0], absx[e]))
        else:
            f += 1
    # over-cap boost frames: velX high byte +1 while ALREADY at/over the 832 cap (the §4g type-0x13
    # INC ram_0094). The >=832 filter excludes the natural high-byte carries during 0->832 accel.
    boosts = []
    for fr_i in range(1, NF):
        prev_v = fr(fr_i-1)[0x94]*256 + fr(fr_i-1)[0x90]
        if fr(fr_i)[0x94] == fr(fr_i-1)[0x94] + 1 and prev_v >= 832:
            boosts.append(absx[fr_i-1])  # start-of-frame posX (matches the interval launchX)
    out = []
    out.append("#pragma once")
    out.append("// GENERATED by tools/extract_track.py --emit-header from tas.ram. Do not edit by hand.")
    out.append("// Reward-fidelity-first track geometry: airborne posX intervals + §4g over-cap boost posX.")
    out.append("// (velX is pinned at 832 through the jump phase, so posX-keyed airborne intervals are")
    out.append("//  deterministic for the forced route. Predictive jump/arc is the documented follow-up.)")
    out.append("#include <cstddef>")
    out.append("namespace excitebike {")
    out.append("struct AirInterval { float launchX, landX; };")
    out.append(f"static constexpr AirInterval kAirIntervals[] = {{")
    for (a,b) in intervals:
        out.append(f"  {{{a:.4f}f, {b:.4f}f}},")
    out.append("};")
    out.append(f"static constexpr size_t kNumAirIntervals = {len(intervals)};")
    out.append(f"static constexpr float kBoostX[] = {{ {', '.join(f'{x:.4f}f' for x in boosts)} }};")
    out.append(f"static constexpr size_t kNumBoosts = {len(boosts)};")
    out.append("} // namespace excitebike")
    open('source/track_data.hpp','w').write("\n".join(out)+"\n")
    print(f"wrote source/track_data.hpp: {len(intervals)} air intervals, {len(boosts)} boosts")
