#!/usr/bin/env python3
"""Generate source/track_sections.hpp (C++) from docs/track_sections.txt — the per-section feature
lists (pos,type) the section machinery scans. Game data (like track_layout.hpp): regenerable, gitignored.

Usage: python3 tools/gen_sections_header.py
"""
import os, re
os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
secs = []
for line in open('docs/track_sections.txt'):
    m = re.match(r'\s*sec\s+(\d+)\s+@\S+\s+\(\d+ feats\):\s*(.*)', line)
    if not m: continue
    feats = [(int(p), int(t, 16)) for p, t in (tok.split(':') for tok in m.group(2).split())]
    secs.append(feats)

out = ['#pragma once',
       '// GENERATED by tools/gen_sections_header.py from docs/track_sections.txt.',
       '// Per-section terrain feature lists (in-section pos, type) for the section machinery (sub_E73B).',
       '#include <cstdint>', '#include <cstddef>', 'namespace excitebike {',
       'struct Feat { uint8_t pos; uint8_t type; };']
for i, feats in enumerate(secs):
    body = ','.join('{%d,0x%02X}' % (p, t) for p, t in feats)
    out.append('static constexpr Feat kSec%d[] = {%s};' % (i, body))
out.append('static constexpr const Feat* kSections[%d] = {%s};' % (len(secs), ','.join('kSec%d' % i for i in range(len(secs)))))
out.append('static constexpr uint8_t kSectionLen[%d] = {%s};' % (len(secs), ','.join(str(len(f)) for f in secs)))
out.append('static constexpr size_t kNumSections = %d;' % len(secs))
out.append('} // namespace excitebike')
open('source/track_sections.hpp', 'w').write('\n'.join(out) + '\n')
print('wrote source/track_sections.hpp:', len(secs), 'sections')
