#pragma once
// GENERATED by tools/extract_track.py --emit-header from tas.ram. Do not edit by hand.
// Reward-fidelity-first track geometry: airborne posX intervals + §4g over-cap boost posX.
// (velX is pinned at 832 through the jump phase, so posX-keyed airborne intervals are
//  deterministic for the forced route. Predictive jump/arc is the documented follow-up.)
#include <cstddef>
namespace excitebike {
struct AirInterval { float launchX, landX; };
static constexpr AirInterval kAirIntervals[] = {
  {1146.0781f, 1427.3281f},
  {1500.3281f, 1705.3281f},
  {1986.5781f, 2257.0781f},
  {2619.8281f, 2904.3281f},
  {3267.0781f, 3489.3281f},
  {3792.8906f, 4070.3906f},
  {4123.1406f, 4480.6406f},
  {4486.6719f, 5457.1406f},
  {5477.2344f, 6447.7031f},
  {7146.9219f, 8042.0469f},
  {8062.1406f, 8694.0469f},
  {8700.0781f, 9724.7969f},
  {9806.0312f, 10120.4062f},
  {10136.3750f, 10432.7969f},
  {10448.7656f, 11328.9531f},
  {11392.0781f, 12157.3281f},
};
static constexpr size_t kNumAirIntervals = 16;
static constexpr float kBoostX[] = { 3792.8906f, 4123.1406f, 4486.6719f, 9806.0312f, 10136.3750f, 10448.7656f };
static constexpr size_t kNumBoosts = 6;
} // namespace excitebike
